name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Deploy to Render
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
    
    - name: Deployment Success
      if: success()
      run: echo "✅ Deployment triggered successfully!"
    
    - name: Deployment Failed
      if: failure()
      run: echo "❌ Deployment failed. Check the logs above."
